name: Deploy to Steam

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build web version
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
        run: npm run build

      - name: Build Electron (unpacked)
        run: npx electron-builder build --win --x64 --dir
        env:
          CSC_IDENTITY_AUTO_DISCOVERY: false

      - name: Prepare Steam app manifest
        run: |
          echo "Creating Steam app manifest..."
          $content = @"
          "appbuild"
          {
              "appid" "${{ secrets.STEAM_APP_ID }}"
              "desc" "Skull Hotel"
              "buildoutput" "build_output"
              "contentroot" "dist-electron/win-unpacked"
              "setlive" "beta"
              "preview" "0"
              "depots"
              {
                  "${{ secrets.STEAM_DEPOT_ID }}"
                  {
                      "FileMapping"
                      {
                          "LocalPath" "*"
                          "DepotPath" "."
                          "recursive" "1"
                      }
                  }
              }
          }
          "@
          $content | Out-File -FilePath .\app_build.vdf -Encoding ascii

      - name: Install Steam CMD
        uses: CyberAndrii/setup-steamcmd@v1

      - name: Deploy to Steam
        run: |
          steamcmd +login ${{ secrets.STEAM_USERNAME }} ${{ secrets.STEAM_PASSWORD }} +run_app_build "${{ github.workspace }}\app_build.vdf" +quit
