name: Deploy to Steam

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build for Steam
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID }}
        run: |
          npm run build
          npm run electron:build

      - name: Setup Steam SDK
        run: |
          mkdir -p steam
          cd steam
          wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
          tar -xvzf steamcmd_linux.tar.gz
          ./steamcmd.sh +quit

      - name: Deploy to Steam
        env:
          STEAM_API_KEY: ${{ secrets.STEAM_API_KEY }}
          STEAM_APP_ID: ${{ secrets.STEAM_APP_ID }}
          STEAM_DEPOT_ID: ${{ secrets.STEAM_DEPOT_ID }}
        run: |
          cd steam
          ./steamcmd.sh +login $STEAM_API_KEY \
            +app_update $STEAM_APP_ID validate \
            +app_build $STEAM_APP_ID $STEAM_DEPOT_ID \
            +quit
